name: bloc_example
description: A new Flutter project.

dependencies:
  flutter_web: any
  flutter_web_ui: any
  rxdart: ^0.22.0

dev_dependencies:
  build_runner: ^1.2.2
  build_web_compilers: ^1.1.0

  test: ^1.3.4

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui  